### ISSUE TITLE
Government proposals 

### ISSUE THREAD

**Issue by catShaark** [realiotech/multi-staking#16]
We need to define government proposals as stated in the spec, and the respective handler for each gov proposals.

Sub tasks:
- [ ] Add Token Proposal
- [ ] Change Token Proposal
- [ ] Remove Token Proposal

**Comment by jiujiteiro** [comment]
Sub tasks:
- [ ] Add Token Proposal
- [ ] Change Token Proposal
- [ ] Remove Token Proposal
