### ISSUE TITLE
Modules need to be migrated

### ISSUE THREAD

**Issue by neitdung** [realiotech/multi-staking#46]
- **Staking**: migrate data from fork module.
- **Distribution**: `DelegatorStartingInfo`, `ValidatorHistoricalRewards`, `DelegatorWithdrawAddr`, `ValidatorCurrentRewards`, `ValidatorAccumulatedCommission`, `ValidatorOutstandingRewards`, `ValidatorSlashEvent`
- **Slashing**: `ValidatorSigningInfo`, `ValidatorMissedBlockBitArray`

**Comment by jiujiteiro** [comment]
closing.
