### ISSUE TITLE
Feat: Refactor for more readability

### ISSUE THREAD

**Issue by catShaark** [realiotech/multi-staking#63]
We re-define some of the core concepts of this module and need to change the respective code:

- The module no longer have the concept of `Bond` and `SDKBond`/ `Unbond` and `SDKUnbond` as previously described in the spec, we change it to `Lock` and `Bond`/ `Unlock` and `Unbond`. The related concepts like `BondToken`, `SDKBondToken` will be changed accordingly to `MultiStakingCoin` and `BondCoin`.  `MultiStakingCoin` will be locked as oposed to `BondToken` will be bond.
- We also introduce the new concept of `MultiStakingLock`\`MultiStakingUnlock` to which is data structures used to keep tracks of amount the that is `locked`\`unlocked` in the process of `Lock` and `Bond` and `Unlock` and `Unbond`. Thus, the module store will no longer has `DV Pair SDK Bond Tokens` and `DV Pair Bond Token` entries but instead `MultiStakingLock` and `MultiStakingUnlock` entries.
- We also rename `intermediary account` to `intermediary delegator`, as well as the mechanism to create `intermediary delegator` from hashing to appending one byte. This in turn change the `intermediary account` store from a map from `intermediary delegator` -> `DelegatorAddr` to a just a set of `intermediary delegator` as we can infer `DelegatorAddr` directly from `intermediary delegator`, not relying on store for mapping.
- We remove `MemStore` from the module.
- There're a lot of variable and function needs to be renamed accordingly. More details will be provided in the sub-issues.

Sub tasks:

- [x] #64
- [x] #65
- [x] #68
- [x] #73
- [x] Rewrite the spec

**Comment by jiujiteiro** [comment]
closing after call with @catShaark on 14/3/24
